### ISSUE TITLE
Cannot pull the tradfri-mqtt image into docker

### ISSUE THREAD

**Issue by hoorna** [hemtjanst/tradfri-mqtt#22]
When I try to pull the tradfri-mqtt image in to my docker instance I get an error. I use the following command:

    docker pull ghcr.io/hemtjanst/tradfri-mqtt

Next I get the following output:

    Using default tag: latest
    Error response from daemon: manifest unknown

It doesn't make any difference when I define a tag as v0.1.4 for example. I then also the get: manifest unknown. What am I doing?wrong?

**Comment by daenney** [comment]
It's not published on GHCR I'm afraid. The README has it as `hemtjanst/tradfri-mqtt`, meaning Docker Hub. Unfortunately that organisation got swept up in one of the many Docker Hub usage and pricing overhauls so it's gone now. You can still build it directly yourself by cloning the repository and running a `docker build .`.

However, we haven't developed this in years since we've stopped using the Trådfri gateway. I'm not entirely certain it works anymore with current firmware versions of the original Trådfri gateway. If you're looking to get started with this today, I would probably suggest using Home Assistant instead, with [their built-in support for Trådfri](https://www.home-assistant.io/integrations/tradfri/). They can also [publish services on MQTT](https://www.home-assistant.io/integrations/mqtt/#publish--dump-services) which lets you recreate what this project does, but with a supported software stack.

**Comment by hoorna** [comment]
@daenney, thanks for your very clear information. That explains why I sadly cannot pull the tradfri-mqtt image.

You wrote that it is still possible to build the image myself "by cloning the respository and running a docker build ..". You also wrote that you are not shure if a container -after building the image- will work with the Tradfri gateway these days. Nevertheless I want to give this a try (because I used tradfri-mqtt before and it was then working flawlessly). However I have never cloned and build a image from scratch before. Can you provide me some information (or probably an internet link) about how can I do this? This would help me a lot further.

Thanks in advance!

**Comment by bonan** [comment]
The image is still available at https://hub.docker.com/r/bonan/tradfri-mqtt

This should work:

`docker pull bonan/tradfri-mqtt`

**Comment by hoorna** [comment]
@bonan, thanks for your information and help. I pulled the image and it is still working. With the docker-compose file which a created a long time ago it worked immediately (of course after editing the image location).

In the log I find the following warnings: 

- (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
- (Use `node --trace-deprecation ...` to show where the warning was created)

It seems that they do not prevent the container from operating normally on this moment.

**Comment by hoorna** [comment]
I have played around a bit with the Tradfri-mqtt output in my MQTT broker.

I was hoping to see that pressing an IKEA remote creates an immediate message for the remote itself in the MQTT broker. But sadly that's not the case. Apparently Tradfri-mqtt do not send MQTT messages to the broker when a remote control is pressed. Of course, a message is sent for the device that is been linked with the to remote control.

Is my conclusion correct? Can I do something about this or can something be done about it?

My goal is to use the IKEA remote to control non-IKEA appliances. I want to do that by reading out the MQTT broker using the MQTT integration in Home Assistant. But then it is necessary that Tradfri MQTT sends a message to the MQTT broker as soon as a button on the IkEA remote control is pressed.

**Comment by bonan** [comment]
> Can I do something about this or can something be done about it?

No. The Trådfri gateway does not send any messages when the remote is used on its own, so it's impossible for tradfri-mqtt to implement that feature.

You need to use [zigbee2mqtt](https://zigbee2mqtt.io) or similar with a supported ZigBee gateway/stick

**Comment by hoorna** [comment]
Thanks for your reply. It's not the answer I was hoping for but what I although expected. Pitty that the Tradri hub does not sent messages when a remote button is pressed. Thanks for the Zigbee tip.
